name: identity
namespace: identity
registry: registry.steffbeckers.eu/identity
services:
  - name: identityserver
    project: IdentityServer/IdentityServer.csproj
    env:
      - ConnectionStrings__IdentityServerDb=Server=mssql;Database=IdentityServer;User ID=sa;Password=OJPVz3waeUwkYBls1fqU;MultipleActiveResultSets=true;
  - name: test-api
    project: Test.API/Test.API.csproj
    env:
      - IdentityServer=https://sso.steffbeckers.eu
      - API=https://api.test.sso.steffbeckers.eu/api
  - name: test-mvc
    project: Test.MVC/Test.MVC.csproj
    env:
      - IdentityServer=https://sso.steffbeckers.eu
      - API=https://api.test.sso.steffbeckers.eu/api
  - name: test-angular
    image: registry.steffbeckers.eu/identity/test-angular
